### ISSUE TITLE
MoErgo's Glove80's triggering the assert "Number of keys on layer {} does not match physical layout specification" 

### ISSUE THREAD

**Issue by x10an14** [caksoylar/keymap-drawer#65]
## Steps to reproduce
1. Git clone `github.com/x10an14/glove80-layout`
1. `cd glove80-layout && git checkout ce86ca203ee12b3d2af95831cd71b2432ec16f1c`
1. `keymap parse --zmk-keymap config/glove80.keymap | keymap draw - > keymap.svg`

<details>
<summary>The above produces the following result</summary>

```
-> $ keymap parse --zmk-keymap config/glove80.keymap | keymap draw - > keymap.svg
Traceback (most recent call last):
  File "/home/x10an14/.local/bin/keymap", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/x10an14/.local/pipx/venvs/keymap-drawer/lib/python3.11/site-packages/keymap_drawer/__main__.py", line 178, in main
    draw(args, config.draw_config)
  File "/home/x10an14/.local/pipx/venvs/keymap-drawer/lib/python3.11/site-packages/keymap_drawer/__main__.py", line 42, in draw
    drawer = KeymapDrawer(
             ^^^^^^^^^^^^^
  File "/home/x10an14/.local/pipx/venvs/keymap-drawer/lib/python3.11/site-packages/keymap_drawer/draw/draw.py", line 24, in __init__
    self.keymap = KeymapData(config=config, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for KeymapData
__root__
  Number of keys on layer "Norwegian" (82) does not match physical layout specification (80) (type=assertion_error)
```

</details>

---

### Potential causes (afaict)
1. Parsing of nested custom zmk actions?
     Ref. the line/colum it complains about (afaict): `&homey_left LCTRL &norwegian_ae`
1. Something similar to #21?

---

## In any regards
I loved it when your tool worked! And I wanted to state my appreciation for this tool and your efforts =)

**Comment by x10an14** [comment]
I'm pretty sure it's got to do with my added layering of that commit, since it seems to work with the previous commit:
![keymap](https://github.com/caksoylar/keymap-drawer/assets/710608/a25a7dd0-1e4f-482e-a7c0-f0b128bab1ec)
