### ISSUE TITLE
bug: `draw_separate` does not work anymore

### ISSUE THREAD

**Issue by englmaxi** [caksoylar/keymap-drawer#77]
I noticed that with yesterdays commit [`18e8d72`](https://github.com/caksoylar/keymap-drawer/commit/18e8d7284c7b93f24a71d4feb1745a1a7bd96b04), I get an [error](https://github.com/englmaxi/zmk-config/actions/runs/8298405052) during parsing:

```
Traceback (most recent call last):
  File "/home/runner/.local/bin/keymap", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.local/lib/python3.10/site-packages/keymap_drawer/__main__.py", line 180, in main
    parse(args, config.parse_config)
  File "/home/runner/.local/lib/python3.10/site-packages/keymap_drawer/__main__.py", line 70, in parse
    parsed = ZmkKeymapParser(config, args.columns, base_keymap=base, layer_names=args.layer_names).parse(
  File "/home/runner/.local/lib/python3.10/site-packages/keymap_drawer/parse/parse.py", line 90, in parse
    layout, keymap_data = self._parse(in_buf.read(), in_buf.name)
  File "/home/runner/.local/lib/python3.10/site-packages/keymap_drawer/parse/zmk.py", line 238, in _parse
    combos = self._get_combos(dts)
  File "/home/runner/.local/lib/python3.10/site-packages/keymap_drawer/parse/zmk.py", line 202, in _get_combos
    combos.append(ComboSpec(**(combo | cfg_combo)))
TypeError: keywords must be strings
```

I found that `draw_separate: true` on some of my combos in `zmk_combos` is the reason for this ([It works without](https://github.com/englmaxi/zmk-config/commit/047d336fd5dea730b238055085f2218ac197840f)).

I don't know if my config is set up wrongly or if there is a mistake on my side, but I did not find anything obvious.

**Comment by caksoylar** [comment]
This is probably a regression from the Pydantic upgrade, thanks for reporting. Let me have a look, hopefully fix it and add it to my internal test cases.

**Comment by caksoylar** [comment]
@englmaxi Can you test again? Should be fixed now.

**Comment by englmaxi** [comment]
Yes, it now works. Thank you for the fast fix! 🎉
